name: "Stage1-1202-uv"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 2337

data_type: "joint-semantic-datamodule"
data:
  batch_size: 1
  width: 1024 # 512
  height: 1024 # 768
  camera_distance_range: [1.25, 2.3] # 2 - 3
  fovy_range: [45, 50]
  elevation_range: [-10, 45]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  eval_camera_distance: 2.1 # 3.0
  eval_fovy_deg: 45.

system_type: "smpl-human-uv-system"
system:
  stage: coarse
  geometry_type: "smpl-plus-uv"
  geometry:
    radius: 1.0
    model_type: "smplx"
    gender: "male"
    fix_geometry: false
    fix_pose: false

  material_type: "diffuse-with-point-light-material-uv"
  material:
    ambient_only_steps: 0
    soft_shading: true

  # material_type: "no-material"
  # material:
  #   n_output_dims: 3
  #   color_activation: sigmoid

  background_type: "neural-environment-map-background"
  background:
    color_activation: sigmoid
    random_aug: true

  renderer_type: "nvdiff-rasterizer-smpl-uv"
  renderer:
    context_type: cuda

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
    prompt: ???
    front_threshold: 30.
    back_threshold: 30.
    semantic_prompt: true

  guidance_type: "controlnet-vsd-smpl-guidance-uv"
  guidance:
    pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
    pretrained_model_name_or_path_lora: "runwayml/stable-diffusion-v1-5"
    guidance_scale: 100. #7.5
    min_step_percent: 0.02
    max_step_percent: 0.98
    max_step_percent_annealed: 0.5
    anneal_start_step: 5000

  # prompt_processor_type: "deep-floyd-prompt-processor"
  # prompt_processor:
  #   pretrained_model_name_or_path: "DeepFloyd/IF-I-XL-v1.0"
  #   semantic_prompt: true
  #   prompt: ???

  # guidance_type: "deep-floyd-guidance"
  # guidance:
  #   pretrained_model_name_or_path: "DeepFloyd/IF-I-XL-v1.0"
  #   guidance_scale: 20.
  #   weighting_strategy: sds
  #   min_step_percent: 0.02
  #   max_step_percent: 0.98

  loggers:
    wandb:
      enable: false
      project: "threestudio"

  loss:
    lambda_vsd: 1.
    lambda_sds: 1.
    lambda_lora: 1.
    lambda_orient: 0.
    lambda_sparsity: 10.
    lambda_normal_consistency: 500. # [2000, 10000., 70000.0, 5000]
    lambda_laplacian_smoothness: 500. # [2000, 10000., 70000.0, 5000]
    lambda_opaque: [10000, 0.0, 1000.0, 10001]
    lambda_z_variance: 0.
    lambda_sdf: 1.0
    lambda_disp_reg: 500.0
    lambda_albedo_smooth: 0.0 # [1200, 0.0, 5.0, 1201]
  optimizer:
    name: Adan
    args:
      eps: 1.0e-8
      weight_decay: 2.0e-5
      max_grad_norm: 5.0
      foreach: False
    params:
      geometry.albedo:
        lr: 0.05 # 0.05 for the original TADA
      geometry.encoding:
        lr: 0.01 # 0.01
      geometry.displacement:
        lr: 0.0001 # 0.0003
      geometry.betas:
        lr: 0.05 # 0.003
      geometry.feature_network:
        lr: 0.001 # 0.001
      geometry.uv_network:
        lr: 0.005 # 0.001
      # geometry.texture_map:
      #   lr: 0.05 # 0.05 for the original TADA
      background:
        lr: 0.001
      guidance: # for lora. deprecated
        lr: 0.0

trainer:
  max_steps: 15000
  log_every_n_steps: 1
  num_sanity_val_steps: 1 # add sanity check in first step
  val_check_interval: 200
  enable_progress_bar: true
  precision: 32

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
